version: 2
before:
  hooks:
    - go mod tidy
dist: ./dist/go
env:
  - CGO_ENABLED=0
builds:
  - binary: cog
    id: cog
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/cog
    ldflags:
      # COG_VERSION (from Cargo.toml via mise build:cog) overrides git-derived version for snapshots.
      # For tagged releases, COG_VERSION is unset and envOrDefault falls back to .Version (from tag).
      - "-s -w -X github.com/replicate/cog/pkg/global.Version={{ envOrDefault \"COG_VERSION\" .Version }} -X github.com/replicate/cog/pkg/global.Commit={{.Commit}} -X github.com/replicate/cog/pkg/global.BuildTime={{.Date}}"
  - binary: base-image
    id: base-image
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/base-image
    ldflags:
      - "-s -w -X github.com/replicate/cog/pkg/global.Version={{ envOrDefault \"COG_VERSION\" .Version }} -X github.com/replicate/cog/pkg/global.Commit={{.Commit}} -X github.com/replicate/cog/pkg/global.BuildTime={{.Date}}"
archives:
  - formats: [binary]
    ids:
      - cog # for now we only release cog
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end -}}
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: '{{ envOrDefault "COG_VERSION" (printf "%s-dev+g%s" (incpatch .Version) .ShortCommit) }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  draft: true
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-alpha
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto
