"""Type stubs for the coglet native module.

coglet is the Rust execution engine for cog models. It runs predictions
in a subprocess with IPC for crash isolation and memory isolation.

This file is auto-generated by scripts/generate_stubs.py.
Do not edit manually - regenerate with: mise run stubs:generate
"""

from typing import Any, Optional

# Module version
__version__: str

# Classes

class SlotLogWriter:
    """Internal: Log writer that routes output based on prediction context.
    
    Do not instantiate directly.
    """
    def write(self, data: str) -> int: ...
    def flush(self) -> None: ...

class TeeWriter:
    """Internal: Writer that tees output to both coglet and user stream.
    
    Do not instantiate directly.
    """
    def write(self, data: str) -> int: ...
    def flush(self) -> None: ...

# Functions

def active() -> bool:
    """Check if running inside a worker subprocess.

    Returns:
        True when running inside the worker subprocess (after coglet._run_worker()),
        False in the parent process (when calling coglet.serve()).
    """
    ...

def serve(
    predictor_ref: Optional[str] = None,
    host: str = "0.0.0.0",
    port: int = 5000,
    await_explicit_shutdown: bool = False,
    is_train: bool = False,
) -> None:
    """Start the coglet HTTP server.

    Args:
        predictor_ref: Path to predictor like "predict.py:Predictor".
                       If None, only health endpoints are served.
        host: Host to bind to.
        port: Port to listen on.
        await_explicit_shutdown: If True, ignore SIGTERM and wait for
                                  SIGINT or /shutdown endpoint.
        is_train: If True, call train() instead of predict().
    """
    ...

# Internal functions (do not use directly)

def _create_tee_writer(inner: Any, user_stream: Any, name: str) -> TeeWriter:
    """Internal function."""
    ...

def _get_inner_writer(tee: TeeWriter) -> Any:
    """Internal function."""
    ...

def _is_cancelable() -> bool:
    """Internal: Check if we're in a cancelable section.

    Used by Python signal handlers for cancellation.
    """
    ...

def _is_slot_log_writer(value: Any) -> bool:
    """Internal function."""
    ...

def _is_tee_writer(value: Any) -> bool:
    """Internal function."""
    ...

def _run_worker() -> None:
    """Internal: Run as a worker subprocess.

    Called by the orchestrator via:
        python -c "import coglet; coglet._run_worker()"

    Reads Init message from stdin, runs setup, then processes predictions.
    Do not call directly.
    """
    ...
