"""
This type stub file was generated by pyright.
"""

import logging
from typing import Optional
from coglet import file_runner

def pre_setup(logger: logging.Logger, working_dir: str) -> Optional[file_runner.Config]:
    ...

def main() -> int:
    ...

if __name__ == '__main__':
    ...
