"""
This type stub file was generated by pyright.
"""

from typing import Tuple, Union

__all__ = ["__version__", "__version_tuple__", "version", "version_tuple", "__commit_id__", "commit_id"]
TYPE_CHECKING = ...
if TYPE_CHECKING:
    VERSION_TUPLE = Tuple[Union[int, str], ...]
    COMMIT_ID = Union[str, None]
else:
    ...
version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
commit_id: COMMIT_ID
__commit_id__: COMMIT_ID
version = ...
version_tuple = ...
commit_id = ...
