"""
This type stub file was generated by pyright.
"""

import ast
from typing import Callable, List

def format_errs(file: str, lines: List[str], lineno: int, col_offset: int, msg: str, help_msg: str) -> str:
    ...

def visit(root: ast.AST, file: str, name: str, lines: List[str], f: Callable[[ast.AST, str, str, List[str]], List[str]]) -> List[str]:
    ...

def inspect_optional(node: ast.AST, file: str, name: str, lines: List[str]) -> List[str]:
    ...

def inspect(file: str, method: str): # -> None:
    ...

