"""
This type stub file was generated by pyright.
"""

import logging
from dataclasses import dataclass

@dataclass(frozen=True)
class Config:
    module_name: str
    predictor_name: str
    max_concurrency: int
    ...


class FileRunner:
    CANCEL_RE = ...
    REQUEST_RE = ...
    RESPONSE_FMT = ...
    IPC_READY = ...
    IPC_BUSY = ...
    IPC_OUTPUT = ...
    def __init__(self, *, logger: logging.Logger, name: str, ipc_url: str, working_dir: str, config: Config) -> None:
        ...
    
    async def start(self) -> int:
        ...
    


