"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict
from coglet import adt, api

class AnyType:
    @staticmethod
    def normalize(value: Any) -> Any:
        ...
    
    @staticmethod
    def json_type() -> dict[str, Any]:
        ...
    
    @staticmethod
    def json_encode(value: Any) -> Any:
        ...
    


_any_type = ...
def check_input(adt_ins: Dict[str, adt.Input], inputs: Dict[str, Any]) -> Dict[str, Any]:
    ...

def create_predictor(module_name: str, predictor_name: str, inspect_ast: bool = ...) -> adt.Predictor:
    ...

def get_test_inputs(p: api.BasePredictor, inputs: Dict[str, adt.Input]) -> Dict[str, Any]:
    ...

