"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict
from coglet import adt

def to_json_input(predictor: adt.Predictor) -> Dict[str, Any]:
    ...

def to_json_enums(predictor: adt.Predictor) -> Dict[str, Any]:
    ...

def to_json_output(predictor: adt.Predictor) -> Dict[str, Any]:
    ...

def to_json_schema(predictor: adt.Predictor) -> Dict[str, Any]:
    ...

