"""
This type stub file was generated by pyright.
"""

def now_iso() -> str:
    ...

def output_json(obj): # -> str | dict[Any, Any]:
    ...

def schema_json(obj): # -> str:
    ...

def type_name(tpe) -> str:
    ...

