name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: ["v*.*.*"]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-tag:
    name: "Check Tag"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      is-release: ${{ steps.check-tag.outputs.is-release }}
    steps:
      - name: Check if commit has a version tag
        id: check-tag
        run: |
          if [[ ${{ github.event.workflow_run.head_branch }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is-release=true" >> $GITHUB_OUTPUT
          else
            echo "is-release=false" >> $GITHUB_OUTPUT
          fi

  release-cli:
    name: "CLI"
    needs: check-tag
    if: needs.check-tag.outputs.is-release == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: make cog
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-python-package:
    name: "Python Package"
    needs: check-tag
    if: needs.check-tag.outputs.is-release == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Build Python package
        run: |
          pip install build
          python -m build --wheel
      - name: Push Python package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages-dir: dist
